// This file will be auto-generated by Supabase CLI
// Run: npx supabase gen types typescript --project-id <your-project-id> > types/database.types.ts
// For now, this is a placeholder

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      // Tables will be defined here after running Supabase CLI
    };
    Views: {
      // Views will be defined here
    };
    Functions: {
      // Functions will be defined here
    };
    Enums: {
      // Enums will be defined here
    };
  };
}

